name: EcoBack
version: ${version}
main: com.user404_.ecoBack.EcoBack
api-version: '1.21'
description: Backup Player Balances easily
author: user404_
website: https://github.com/deutschich/EcoBack

depend: [Vault]

commands:
  ecoback:
    description: Main command for EcoBack
    usage: /<command> [reload|backup|backups|rollback]
    permission: ecoback.command

permissions:
  ecoback.command:
    description: n.a.
    default: op
  ecoback.backup:
    description: n.a.
    default: op
  ecoback.rollback:
    description: n.a.
    default: true
  ecoback.update.notify:
    description: n.a.
    default: op