name: EcoBack
version: ${version}
main: com.user404_.ecoBack.EcoBack
api-version: '1.21'
description: Backup Player Balances easily
author: user404_
website: https://github.com/deutschich/EcoBack

depend: [Vault]

commands:
  ecoback:
    description: Main command for EcoBack
    usage: /<command> [backup|backups|rollback|reload]
    permission: ecoback.admin

permissions:
  ecoback.admin:
    description: Allows use of all EcoBack commands
    default: op
  ecoback.backup:
    description: Allows creating a backup
    default: op
  ecoback.rollback:
    description: Allows restoring a backup
    default: op
  ecoback.update.notify:
    description: Receives update notifications on join
    default: op